networks:

  default:
    name: nse-net

services:

  python-fastapi-quote:
    build:
      context: ./quote
      dockerfile: Dockerfile
    image: python-fastapi-quote
    ports:
      - "8000:8000"
    command: python ./app/main.py
    container_name: python-fastapi-quote

  python-fastapi-fetcher:
    build:
      context: ./fetcher
      dockerfile: Dockerfile
    image: python-fastapi-fetcher
    ports:
      - "8001:8001"
    command: python ./app/main.py
    container_name: python-fastapi-fetcher
