---  # separates service definitions

# Service 1: python-fastapi-quote
services:
  python-fastapi-quote:
    type: web
    name: python-fastapi-quote
    env: docker
    dockerfilePath: ./quote/Dockerfile
    port: 8000

---  # separates service definitions

# Service 2: python-fastapi-search
services:
  python-fastapi-search:
    type: web
    name: python-fastapi-search
    env: docker
    dockerfilePath: ./search/Dockerfile
    port: 8002

---  # separates service definitions

# Service 3: python-fastapi-fetcher & Main Application
services:
  python-fastapi-fetcher:  # Assuming fetcher is the main functionality
    type: web
    name: python-fastapi-fetcher
    env: docker
    dockerfilePath: ./fetcher/Dockerfile  # Assuming fetcher uses the main.py
    command: python ./app/main.py  # Replace with the actual start command if different
    port: 8002
