services:
  - name: python-fastapi-quote
    env: docker
    dockerfile_path: ./quote/Dockerfile
    env_vars:
      - key: PORT
        value: 8000
    public_ports:
      - 8000
    start_command: python ./app/main.py

  - name: python-fastapi-search
    env: docker
    dockerfile_path: ./search/Dockerfile
    env_vars:
      - key: PORT
        value: 8002
    public_ports:
      - 8002
    start_command: python ./app/main.py

  - name: python-fastapi-fetcher
    env: docker
    dockerfile_path: ./fetcher/Dockerfile
    env_vars:
      - key: PORT
        value: 8001
    public_ports:
      - 8001
    start_command: python ./app/main.py
