services:
  - type: web
    name: python-fastapi-quote
    env: docker
    dockerfilePath: ./quote/Dockerfile
    - key: PORT
      value: 8000

  - type: web
    name: python-fastapi-search
    env: docker
    dockerfilePath: ./search/Dockerfile
    - key: PORT
      value: 8002

  - type: web
    name: python-fastapi-fetcher
    env: docker
    dockerfilePath: ./fetcher/Dockerfile
    - key: PORT
      value: 8001
